- hosts: masters, workers
  name: Setup masters and workers
  remote_user: vagrant
  become: yes
  tasks:
    # Disable swap (Kubeadm requirement)
    - name: Disable SWAP
      shell: |
        swapoff -a
    
    - name: Disable SWAP in fstab (Kubeadm requirement)
      replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        replace: '# \1'
    
    # Configure iptables for Kubeadm
    - name: Load br_netfilter module
      shell: |
        cat <<EOF | sudo tee /etc/modules-load.d/k8s.conf
        br_netfilter
        EOF
    
    - name: Configure iptables to see bridged traffic
      shell: |
        cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
        net.bridge.bridge-nf-call-ip6tables = 1
        net.ipv4.ip_forward                 = 1
        net.bridge.bridge-nf-call-iptables  = 1
        EOF
    
    - name: Read values from all system directories
      shell: sysctl --system
    
    # # Update system packages
    # - name: Update system packages
    #   yum:
    #     name: '*'
    #     state: update
    #   register: update_result

    - name: Install yum-utils
      yum:
        name: yum-utils
        state: present

    - name: Add Docker repository
      shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

    - name: Install Docker and related packages
      yum:
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    # - name: Verify Docker installation
    #   command: docker run hello-world
    #   register: docker_run

    # - name: Assert Docker is running
    #   assert:
    #     that: docker_run.rc == 0
    #     msg: "Docker is not running!"
        
    # Configure Docker daemon
    - name: Create Docker directory
      file:
        path: /etc/docker
        state: directory
        owner: root
        group: root
        mode: 0755
    
    - name: Create Docker daemon configuration file
      copy:
        content: ""
        dest: /etc/docker/daemon.json
        force: no
        owner: root
        group: root
        mode: 0644
    
    - name: Configure Docker daemon
      copy:
        content: |
          {
            "exec-opts": ["native.cgroupdriver=systemd"],
            "log-driver": "json-file",
            "log-opts": {
              "max-size": "100m"
            },
            "storage-driver": "overlay2"
          }
        dest: /etc/docker/daemon.json
        owner: root
        group: root
        mode: 0644
    
    - name: Restart Docker
      systemd:
        name: docker
        state: restarted
        enabled: yes
        daemon-reload: yes
    
    - name: Add current user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
      become: yes

    - name: Add Kubernetes Yum repository
      yum_repository:
        name: kubernetes
        description: Kubernetes repository
        baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        enabled: yes
        gpgkey:
          - https://packages.cloud.google.com/yum/doc/yum-key.gpg
          - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
        gpgcheck: yes
        state: present

    - name: Install kubelet, kubeadm and kubectl
      yum:
        name:
          - kubelet-1.28.*
          - kubeadm-1.28.*
          - kubectl-1.28.*
        state: present

    - name: Enable kubelet service
      systemd:
        name: kubelet
        enabled: yes

    - name: Load br_netfilter kernel module
      modprobe:
        name: br_netfilter
        state: present

    - name: Set net.bridge.bridge-nf-call-iptables
      sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: 1
        state: present

    - name: Set net.ipv4.ip_forward
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present

- hosts: masters
  name: Init cluster and join masters
  remote_user: vagrant
  become: yes
  tasks:
    - name: Reset existing cluster
      command: kubeadm reset -f

    - name: Remove .kube in user home directory
      file:
        path: ~/.kube
        state: absent

    - name: Remove /etc/kubernetes/manifests directory
      file:
        path: /etc/kubernetes/manifests
        state: absent

    - name: Remove /var/lib/etcd directory
      file:
        path: /var/lib/etcd
        state: absent

    - name: Init kubernetes cluster
      shell: |
        kubeadm init --control-plane-endpoint={{ cluster_vip }}:6443 --upload-certs --apiserver-advertise-address=192.168.56.134 --pod-network-cidr=192.168.0.0/16
      run_once: yes
      delegate_to: "192.168.56.134"

    # Add Calico Network
    - name: Download Calico manifest
      get_url:
        url: https://docs.projectcalico.org/manifests/calico.yaml
        dest: /home/vagrant/calico.yaml
        mode: '0644'
      run_once: yes
      delegate_to: "192.168.56.134"

    - name: Deploy Calico network
      shell: kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f /home/vagrant/calico.yaml
      run_once: yes
      delegate_to: "192.168.56.134"

    - name: Print join command
      shell: kubeadm token create --print-join-command
      register: kubernetes_join_command
      run_once: yes
      delegate_to: "192.168.56.134"

    - name: Copy join command to local
      become: no
      local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777
      run_once: yes
      delegate_to: "192.168.56.134"

    - name: Generate certificate key
      shell: kubeadm init phase upload-certs --upload-certs
      register: kubernetes_certificate_key
      run_once: yes
      delegate_to: "192.168.56.134"

    - name: Execute master join command
      become: yes
      when: inventory_hostname != "192.168.56.134"
      shell: "{{ kubernetes_join_command.stdout_lines[0] }} --control-plane --certificate-key {{ kubernetes_certificate_key.stdout_lines[2] }} --apiserver-advertise-address={{ inventory_hostname }}"

    # This got updated after the video
    # Because of https://github.com/kubernetes/kubernetes/issues/60835#issuecomment-395931644
    - name: Edit kubeadm.conf
      blockinfile:
        path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
        block: |
          Environment="KUBELET_EXTRA_ARGS=--node-ip={{ inventory_hostname }}"

    - name: Restart kubelet service
      service:
        name: kubelet
        daemon-reload: yes
        state: restarted

    - name: Create directory for kube config
      file:
        path: /home/vagrant/.kube
        state: directory
        owner: vagrant
        group: vagrant
        mode: 0755

    - name: Copy /etc/kubernetes/admin.conf to user home directory
      become_user: root
      become_method: sudo
      become: yes
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/vagrant/.kube/config
        remote_src: yes
        owner: vagrant
        group: vagrant
        mode: '0644'

- hosts: workers
  name: Join workers
  remote_user: vagrant
  become: yes
  tasks:
    - name: Reset existing cluster
      shell: kubeadm reset -f

    - name: Remove .kube in user home directory
      shell: rm -rf .kube

    - name: Remove /etc/kubernetes/manifests directory
      shell: rm -rf /etc/kubernetes/manifests

    - name: Copy join command to workers
      copy:
        src: /tmp/kubernetes_join_command
        dest: /tmp/kubernetes_join_command
        mode: 0777

    - name: Execute worker join command
      shell: sh /tmp/kubernetes_join_command

    # This got updated after the video
    # Because of https://github.com/kubernetes/kubernetes/issues/60835#issuecomment-395931644
    - name: Edit kubeadm.conf
      blockinfile:
        path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
        block: |
          Environment="KUBELET_EXTRA_ARGS=--node-ip={{ inventory_hostname }}"

    - name: Restart kubelet service
      service:
        name: kubelet
        daemon-reload: yes
        state: restarted
