all:
  children:
    masters:
      hosts:
        10.16.150.138: null
        10.16.150.139: null
        10.16.150.140: null

    workers:
      hosts:
        10.16.150.134: null
        10.16.150.135: null
        10.16.150.136: null
