cluster_vip: 10.16.150.252
master_nodes:
  - 10.16.150.138
  - 10.16.150.139
  - 10.16.150.140
worker_nodes:
  - 10.16.150.134
  - 10.16.150.135
  - 10.16.150.136
lb:
  - 10.16.150.132
  - 10.16.150.133