---

- hosts: masters, workers
  name: Setup masters and workers
  remote_user: ci
  become: yes
  tasks:
    # https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#before-you-begin
    - name: disable SWAP (Kubeadm requirement)
      shell: |
        swapoff -a

    - name: disable SWAP in fstab (Kubeadm requirement)
      replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        replace: '# \1'

    - name: Load br_netfilter module
      shell: |
        cat <<EOF | sudo tee /etc/modules-load.d/k8s.conf
        br_netfilter
        EOF

    - name: Configure iptables to see bridged traffic
      shell: |
        cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
        net.bridge.bridge-nf-call-ip6tables = 1
        net.ipv4.ip_forward                 = 1
        net.bridge.bridge-nf-call-iptables = 1
        EOF

    - name: Read values from all system directories
      shell: sysctl --system

    # https://docs.docker.com/engine/install/ubuntu/#installation-methods
    - name: Install packages to allow yum to use a repository over HTTPS
      yum:
        name:
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: yes
      when: ansible_os_family == "RedHat"

    - name: Add Dockerâ€™s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Get Ubuntu release version
      shell: lsb_release -cs
      register: ubuntu_version

    - name: Get architecture
      shell: dpkg --print-architecture
      register: architecture

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch={{ architecture.stdout }}] https://download.docker.com/linux/ubuntu {{ ubuntu_version.stdout }} stable"
        state: present
        filename: docker

    - name: Update apt packages
      apt:
        update_cache: "yes"
        force_apt_get: "yes"

    - name: Install Docker engine
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: yes

    # https://kubernetes.io/docs/setup/production-environment/container-runtimes/#docker
    - name: Create Docker directory
      file:
        path: /etc/docker
        state: directory

    - name: Create Docker daemon empty file
      copy:
        content: ""
        dest: /etc/docker/daemon.json
        force: no

    - name: Configure Docker daemon
      shell: |
        cat <<EOF | sudo tee /etc/docker/daemon.json
        {
          "exec-opts": ["native.cgroupdriver=systemd"],
          "log-driver": "json-file",
          "log-opts": {
            "max-size": "100m"
          },
          "storage-driver": "overlay2"
        }
        EOF

    - name: Restart Docker
      systemd:
        name: docker
        state: restarted
        enabled: yes
        daemon-reload: yes

    - name: Add current user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
      become: yes

    - name: Add Google Cloud public signing key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Add Kubernetes repository
      apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: kubernetes
        mode: 0600

    - name: Install kubelet, kubeadm and kubectl
      apt:
        name:
          - kubeadm=1.28.*
          - kubectl=1.28.*
          - kubelet=1.28.*
        state: present

    - name: Enable kubelet service
      service:
        name: kubelet
        enabled: yes

    - name: load br_netfilter kernel module
      modprobe:
        name: br_netfilter
        state: present

    - name: set bridge-nf-call-iptables
      sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: 1

    - name: set ip_forward
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
        
- hosts: masters
  name: Init cluster and join masters
  remote_user: ci
  become: yes
  tasks:
    - name: Reset existing cluster
      shell: kubeadm reset -f

    - name: Remove .kube in user home directory
      shell: rm -rf .kube

    - name: Remove /etc/kubernetes/manifests directory
      shell: rm -rf /etc/kubernetes/manifests

    - name: Remove /var/lib/etcd directory
      shell: rm -rf /var/lib/etcd

    - name: Init kubernetes cluster
      shell: kubeadm init --control-plane-endpoint={{ cluster_vip }}:6443 --upload-certs --apiserver-advertise-address=192.168.56.21 --pod-network-cidr=192.168.0.0/16
      run_once: yes
      delegate_to: "192.168.56.21"

    # Add Calico Network
    - name: Download Calico manifest
      get_url:
        url: https://docs.projectcalico.org/manifests/calico.yaml
        dest: /home/ci/calico.yaml
        mode: '0644'
      run_once: yes
      delegate_to: "192.168.56.21"

    - name: Deploy Calico network
      shell: kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f /home/ci/calico.yaml
      run_once: yes
      delegate_to: "192.168.56.21"

    - name: Print join command
      shell: kubeadm token create --print-join-command
      register: kubernetes_join_command
      run_once: yes
      delegate_to: "192.168.56.21"

    - name: Copy join command to local
      become: no
      local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777
      run_once: yes
      delegate_to: "192.168.56.21"

    - name: Generate certificate key
      shell: kubeadm init phase upload-certs --upload-certs
      register: kubernetes_certificate_key
      run_once: yes
      delegate_to: "192.168.56.21"

    - name: Execute master join command
      become: yes
      when: inventory_hostname != "192.168.56.21"
      shell: "{{ kubernetes_join_command.stdout_lines[0] }} --control-plane --certificate-key {{ kubernetes_certificate_key.stdout_lines[2] }} --apiserver-advertise-address={{ inventory_hostname }}"

    # This got updated after the video
    # Because of https://github.com/kubernetes/kubernetes/issues/60835#issuecomment-395931644
    - name: Edit kubeadm.conf
      blockinfile:
        path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
        block: |
          Environment="KUBELET_EXTRA_ARGS=--node-ip={{ inventory_hostname }}"

    - name: Restart kubelet service
      service:
        name: kubelet
        daemon-reload: yes
        state: restarted

    - name: Create directory for kube config
      file:
        path: /home/ci/.kube
        state: directory
        owner: ci
        group: ci
        mode: 0755

    - name: Copy /etc/kubernetes/admin.conf to user home directory
      become_user: root
      become_method: sudo
      become: yes
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ci/.kube/config
        remote_src: yes
        owner: ci
        group: ci
        mode: '0644'

- hosts: workers
  name: Join workers
  remote_user: ci
  become: yes
  tasks:
    - name: Reset existing cluster
      shell: kubeadm reset -f

    - name: Remove .kube in user home directory
      shell: rm -rf .kube

    - name: Remove /etc/kubernetes/manifests directory
      shell: rm -rf /etc/kubernetes/manifests

    - name: Copy join command to workers
      copy:
        src: /tmp/kubernetes_join_command
        dest: /tmp/kubernetes_join_command
        mode: 0777

    - name: Execute worker join command
      shell: sh /tmp/kubernetes_join_command

    # This got updated after the video
    # Because of https://github.com/kubernetes/kubernetes/issues/60835#issuecomment-395931644
    - name: Edit kubeadm.conf
      blockinfile:
        path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
        block: |
          Environment="KUBELET_EXTRA_ARGS=--node-ip={{ inventory_hostname }}"

    - name: Restart kubelet service
      service:
        name: kubelet
        daemon-reload: yes
        state: restarted
